# Generated by Django 6.0.3 on 2026-04-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('table_no', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('A', 'Available'), ('O', 'Occupied')], default='A', max_length=1)),
            ],
        ),
    ]
