# Generated by Django 6.0.3 on 2026-07-06 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('home', '0001_0001_initial_setup'), ('home', '0012_alter_tableinfo_status_order_squashed_0015_menucategory_delete_order'), ('home', '0016_menuitem'), ('home', '0017_menuvariant'), ('home', '0018_alter_menuitem_order_with_respect_to'), ('home', '0019_alter_menuitem_order_with_respect_to'), ('home', '0020_alter_menuitem_options'), ('home', '0021_alter_menuitem_options'), ('home', '0022_alter_menuitem_options'), ('home', '0023_alter_menuitem_options')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('table_no', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('A', 'Available'), ('O', 'Occupied')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='home.menucategory')),
            ],
            options={
                'unique_together': {('category', 'name')},
                'order_with_respect_to': None,
            },
        ),
        migrations.CreateModel(
            name='MenuVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='home.menuitem')),
            ],
            options={
                'unique_together': {('item', 'size')},
            },
        ),
    ]
