# Generated by Django 6.0.3 on 2026-04-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('A', 'Available'), ('O', 'Occupied')], max_length=10)),
            ],
        ),
    ]
