# Generated by Django 6.0.3 on 2026-04-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.AlterField(
            model_name='table',
            name='table_no',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
