# Generated by Django 6.0.3 on 2026-08-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cafe',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/cafe_profiles/'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
