# Generated by Django 6.0.3 on 2026-09-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cafe_gstin_cafe_phone_number_cafe_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cafe_profiles/'),
        ),
    ]
