# Generated by Django 6.0.3 on 2026-04-25 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_0001_initial_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableinfo',
            name='status',
            field=models.CharField(choices=[('O', 'Occupied'), ('A', 'Available')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('active', 'Active')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.tableinfo')),
            ],
        ),
    ]
