# Generated by Django 6.0.3 on 2026-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('home', '0012_alter_tableinfo_status_order'), ('home', '0013_alter_order_status'), ('home', '0014_alter_order_status_alter_tableinfo_status'), ('home', '0015_menucategory_delete_order')]

    dependencies = [
        ('home', '0001_0001_initial_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableinfo',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('O', 'Occupied')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
