# Generated by Django 6.0.3 on 2026-04-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('active', 'Active')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('O', 'Occupied')], default='A', max_length=1),
        ),
    ]
