# Generated by Django 6.0.3 on 2026-04-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_menuvariant'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='menuitem',
            order_with_respect_to='category',
        ),
    ]
