# Generated by Django 6.0.3 on 2026-04-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_menuitem_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name']},
        ),
    ]
