# Generated by Django 6.0.3 on 2026-04-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category__name']},
        ),
    ]
