# Generated by Django 6.0.3 on 2026-04-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
    ]
