# Generated by Django 6.0.3 on 2026-07-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_bill_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='base_price',
        ),
        migrations.AlterField(
            model_name='menuvariant',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large'), ('D', 'Default')], max_length=5),
        ),
    ]
