# Generated by Django 6.0.3 on 2026-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_menuitem_base_price_alter_menuvariant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuvariant',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large'), ('D', 'Default')], max_length=10),
        ),
    ]
