# Generated by Django 6.0.3 on 2026-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_menuvariant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuvariant',
            name='size',
            field=models.CharField(choices=[('D', 'Default'), ('S', 'Small'), ('L', 'Large')], default='D', max_length=10),
        ),
    ]
