# Generated by Django 6.0.3 on 2026-07-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_menuvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='items_summary',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='bill',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
